In [1]:
import pandas as pd
import sqlite3

## Что нужно сделать:

1. Создай соединение с базой данных с помощью библиотеки sqlite3.
2. Одним запросом создай в базе новую таблицу datamart, объединив таблицы pageviews и checker.
    - В таблице должны быть колонки: "uid", "labname", "first_commit_ts", "first_view_ts".
    - "first_commit_ts" - новое имя колонки "timestamp" из таблицы checker; это первая отправка для конкретной лабораторной и пользователя.
    - "first_view_ts" - первая временная метка посещения пользователем ленты (newsfeed) из pageviews.
    - Фильтр status = 'ready' должен сохраняться.
    - Фильтр numTrials = 1 должен сохраняться.
    - "labnames" должен входить в список: laba04, laba04s, laba05, laba06, laba06s, и project1.
    - В таблицу должны попадать только пользователи (uid вида user_*), администраторы - исключаются.
    - Колонки "first_commit_ts" и "first_view_ts" должны иметь тип datetime64[ns].
3. С помощью методов Pandas создай два DataFrame: test и control.
    - test содержит пользователей с заполненными значениями в "first_view_ts".
    - control содержит пользователей с пропущенными значениями в "first_view_ts".
    - Замени пропуски в control средним значением "first_view_ts" среди пользователей из test. Сохрани обе таблицы в базе - они понадобятся в следующих упражнениях.
4. Закрой соединение.

In [2]:
db_path = '../data/checking-logs.sqlite'
conn = sqlite3.connect(db_path)

In [3]:
conn.execute("DROP TABLE IF EXISTS datamart;")

In [4]:
conn.execute(
    """
    CREATE TABLE IF NOT EXISTS datamart AS
    SELECT
        c.uid,
        c.labname,
        c.timestamp AS first_commit_ts,
        MIN(p.datetime) AS first_view_ts
    FROM checker c
    LEFT JOIN pageviews p ON c.uid = p.uid
    WHERE c.status = 'ready'
      AND c.numTrials = 1
      AND c.labname IN ('laba04', 'laba04s', 'laba05', 'laba06', 'laba06s', 'project1')
      AND c.uid LIKE 'user_%'
    GROUP BY c.uid, c.labname, c.timestamp;
    """
)

datamart = pd.io.sql.read_sql(
    'SELECT * FROM datamart;',
    conn,
    parse_dates = ["first_commit_ts", "first_view_ts"]
)
datamart[["first_commit_ts", "first_view_ts"]] = datamart[["first_commit_ts", "first_view_ts"]].astype("datetime64[ns]")

In [5]:
print('===Датафрейма datamart===')
datamart

===Датафрейма datamart===

        uid   labname            first_commit_ts              first_view_ts
0    user_1    laba04 2020-04-26 17:06:18.462708 2020-04-26 21:53:59.624136
1    user_1   laba04s 2020-04-26 17:12:11.843671 2020-04-26 21:53:59.624136
2    user_1    laba05 2020-05-02 19:15:18.540185 2020-04-26 21:53:59.624136
3    user_1    laba06 2020-05-17 16:26:35.268534 2020-04-26 21:53:59.624136
4    user_1   laba06s 2020-05-20 12:23:37.289724 2020-04-26 21:53:59.624136
..      ...       ...                        ...                        ...
135  user_8   laba04s 2020-04-19 10:22:35.761944                        NaT
136  user_8    laba05 2020-05-02 13:28:07.705193                        NaT
137  user_8    laba06 2020-05-16 17:56:15.755553                        NaT
138  user_8   laba06s 2020-05-16 20:01:07.900727                        NaT
139  user_8  project1 2020-05-14 15:42:04.002981                        NaT

[140 rows x 4 columns]

In [6]:
datamart.info()

<class 'pandas.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   uid              140 non-null    str
 1   labname          140 non-null    str
 2   first_commit_ts  140 non-null    datetime64[ns]
 3   first_view_ts    59 non-null     datetime64[ns]
dtypes: datetime64[ns](2), str(2)
memory usage: 4.5 KB

In [7]:
print(f'Тип колонок с датами:\n{datamart[['first_commit_ts', 'first_view_ts']].dtypes}')

Тип колонок с датами:
first_commit_ts    datetime64[ns]
first_view_ts      datetime64[ns]
dtype: object

In [8]:
test = datamart[datamart['first_view_ts'].notna()].copy()
control = datamart[datamart['first_view_ts'].isna()].copy()

In [9]:
print('===Датафрейм test===')
test

===Датафрейм test===

         uid   labname            first_commit_ts              first_view_ts
0     user_1    laba04 2020-04-26 17:06:18.462708 2020-04-26 21:53:59.624136
1     user_1   laba04s 2020-04-26 17:12:11.843671 2020-04-26 21:53:59.624136
2     user_1    laba05 2020-05-02 19:15:18.540185 2020-04-26 21:53:59.624136
3     user_1    laba06 2020-05-17 16:26:35.268534 2020-04-26 21:53:59.624136
4     user_1   laba06s 2020-05-20 12:23:37.289724 2020-04-26 21:53:59.624136
5     user_1  project1 2020-05-14 20:56:08.898880 2020-04-26 21:53:59.624136
6    user_10    laba04 2020-04-25 08:24:52.696624 2020-04-18 12:19:50.182714
7    user_10   laba04s 2020-04-25 08:37:54.604222 2020-04-18 12:19:50.182714
8    user_10    laba05 2020-05-01 19:27:26.063245 2020-04-18 12:19:50.182714
9    user_10    laba06 2020-05-19 11:39:28.885637 2020-04-18 12:19:50.182714
10   user_10   laba06s 2020-05-20 07:37:31.175817 2020-04-18 12:19:50.182714
11   user_10  project1 2020-05-12 20:12:28.056618 2020-04-18 12:19:50.182714
24   user_14    laba04 2020-04-18 15:14:00.312338 2020-04-18 10:53:52.623447
25   user_14   laba04s 2020-04-18 22:30:30.247628 2020-04-18 10:53:52.623447
26   user_14    laba05 2020-04-30 11:33:04.523118 2020-04-18 10:53:52.623447
27   user_14  project1 2020-05-05 21:35:43.554986 2020-04-18 10:53:52.623447
34   user_17    laba04 2020-04-23 14:24:29.947554 2020-04-18 10:56:55.833899
35   user_17   laba04s 2020-04-25 12:10:56.414175 2020-04-18 10:56:55.833899
36   user_17    laba05 2020-05-02 13:21:24.045876 2020-04-18 10:56:55.833899
37   user_17    laba06 2020-05-21 15:21:31.567615 2020-04-18 10:56:55.833899
38   user_17   laba06s 2020-05-21 17:39:17.783615 2020-04-18 10:56:55.833899
39   user_17  project1 2020-04-18 07:56:45.408648 2020-04-18 10:56:55.833899
40   user_18    laba04 2020-04-26 19:48:11.822365 2020-04-26 22:49:29.243278
41   user_18   laba04s 2020-04-26 20:03:56.935458 2020-04-26 22:49:29.243278
42   user_18    laba05 2020-05-03 13:01:34.848756 2020-04-26 22:49:29.243278
43   user_18  project1 2020-05-11 10:10:04.166881 2020-04-26 22:49:29.243278
44   user_19    laba04 2020-04-20 19:05:01.297780 2020-04-21 20:30:38.034966
45   user_19    laba05 2020-05-02 15:16:13.586405 2020-04-21 20:30:38.034966
46   user_19    laba06 2020-05-19 10:25:54.121465 2020-04-21 20:30:38.034966
47   user_19   laba06s 2020-05-21 13:27:06.705881 2020-04-21 20:30:38.034966
48   user_19  project1 2020-05-14 10:33:45.495389 2020-04-21 20:30:38.034966
59   user_21    laba04 2020-04-21 17:48:00.487806 2020-04-22 22:40:36.824081
60   user_21   laba04s 2020-04-22 20:09:21.857747 2020-04-22 22:40:36.824081
61   user_21    laba05 2020-05-02 14:05:40.013959 2020-04-22 22:40:36.824081
62   user_21    laba06 2020-05-19 19:30:14.644328 2020-04-22 22:40:36.824081
63   user_21  project1 2020-05-10 15:21:05.442755 2020-04-22 22:40:36.824081
78   user_25    laba04 2020-04-20 19:16:50.673054 2020-05-09 23:54:54.260791
79   user_25   laba04s 2020-04-26 21:07:56.952117 2020-05-09 23:54:54.260791
80   user_25    laba05 2020-05-01 13:02:27.357650 2020-05-09 23:54:54.260791
81   user_25    laba06 2020-05-18 17:07:47.988807 2020-05-09 23:54:54.260791
82   user_25   laba06s 2020-05-20 14:02:26.512032 2020-05-09 23:54:54.260791
83   user_25  project1 2020-05-08 11:10:28.100852 2020-05-09 23:54:54.260791
92   user_28    laba04 2020-04-22 21:47:19.707242 2020-05-10 21:07:50.350946
93   user_28   laba04s 2020-04-26 15:53:44.906136 2020-05-10 21:07:50.350946
94   user_28    laba05 2020-05-01 18:29:11.968537 2020-05-10 21:07:50.350946
95   user_28    laba06 2020-05-17 17:08:48.257050 2020-05-10 21:07:50.350946
96   user_28   laba06s 2020-05-20 20:42:44.423160 2020-05-10 21:07:50.350946
97   user_28  project1 2020-05-12 14:42:19.166414 2020-05-10 21:07:50.350946
104   user_3    laba04 2020-04-23 20:29:14.054364 2020-05-08 10:53:47.123832
105   user_3   laba04s 2020-04-23 20:40:26.883591 2020-05-08 10:53:47.123832
106   user_3    laba05 2020-05-01 11:29:17.988118 2020-05-08 10:53:47.123832
107   user_3    laba06 2020-05-17 09:56:40.480319 2020-05-08 10:53:47.123832
108   user_3   laba06s 2020-05-19 08:42:50.851878 2020-05-08 10:53:47.123832
109   user_3  project1 2020-05-07 21:02:52.885133 2020-05-08 10:53:47.123832
110  user_30    laba04 2020-04-18 13:36:53.971502 2020-04-17 22:46:26.785035
111  user_30   laba04s 2020-04-18 14:51:37.498399 2020-04-17 22:46:26.785035
112  user_30    laba05 2020-05-01 19:31:18.375833 2020-04-17 22:46:26.785035
113  user_30    laba06 2020-05-19 17:53:15.088248 2020-04-17 22:46:26.785035
114  user_30  project1 2020-04-22 12:36:24.053518 2020-04-17 22:46:26.785035

In [10]:
print('===Датафрейм control (до)===')
control

===Датафрейм control (до)===

         uid   labname            first_commit_ts first_view_ts
12   user_11    laba05 2020-05-03 21:06:55.970293           NaT
13   user_11  project1 2020-05-03 23:45:33.673409           NaT
14   user_12    laba04 2020-04-18 17:07:51.767358           NaT
15   user_12   laba04s 2020-04-26 15:42:38.070593           NaT
16   user_12    laba05 2020-05-03 08:39:25.174316           NaT
..       ...       ...                        ...           ...
135   user_8   laba04s 2020-04-19 10:22:35.761944           NaT
136   user_8    laba05 2020-05-02 13:28:07.705193           NaT
137   user_8    laba06 2020-05-16 17:56:15.755553           NaT
138   user_8   laba06s 2020-05-16 20:01:07.900727           NaT
139   user_8  project1 2020-05-14 15:42:04.002981           NaT

[81 rows x 4 columns]

In [11]:
test.info()

<class 'pandas.DataFrame'>
Index: 59 entries, 0 to 114
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   uid              59 non-null     str
 1   labname          59 non-null     str
 2   first_commit_ts  59 non-null     datetime64[ns]
 3   first_view_ts    59 non-null     datetime64[ns]
dtypes: datetime64[ns](2), str(2)
memory usage: 2.3 KB

In [12]:
control.info()

<class 'pandas.DataFrame'>
Index: 81 entries, 12 to 139
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   uid              81 non-null     str
 1   labname          81 non-null     str
 2   first_commit_ts  81 non-null     datetime64[ns]
 3   first_view_ts    0 non-null      datetime64[ns]
dtypes: datetime64[ns](2), str(2)
memory usage: 3.2 KB

In [13]:
mean_first_view_ts = test['first_view_ts'].mean()
control['first_view_ts'] = mean_first_view_ts

In [14]:
print('===Датафрейм control (после)===')
control

===Датафрейм control (после)===

,uid,labname,first_commit_ts,first_view_ts
12,user_11,laba05,2020-05-03 21:06:55.970293,2020-04-27 00:40:05.761783552
13,user_11,project1,2020-05-03 23:45:33.673409,2020-04-27 00:40:05.761783552
14,user_12,laba04,2020-04-18 17:07:51.767358,2020-04-27 00:40:05.761783552
15,user_12,laba04s,2020-04-26 15:42:38.070593,2020-04-27 00:40:05.761783552
16,user_12,laba05,2020-05-03 08:39:25.174316,2020-04-27 00:40:05.761783552
...,...,...,...,...
135,user_8,laba04s,2020-04-19 10:22:35.761944,2020-04-27 00:40:05.761783552
136,user_8,laba05,2020-05-02 13:28:07.705193,2020-04-27 00:40:05.761783552
137,user_8,laba06,2020-05-16 17:56:15.755553,2020-04-27 00:40:05.761783552
138,user_8,laba06s,2020-05-16 20:01:07.900727,2020-04-27 00:40:05.761783552
139,user_8,project1,2020-05-14 15:42:04.002981,2020-04-27 00:40:05.761783552

In [18]:
test.to_sql('test', conn, if_exists='replace', index=False)

ProgrammingError: Cannot operate on a closed database.

In [19]:
control.to_sql('control', conn, if_exists='replace', index=False)

ProgrammingError: Cannot operate on a closed database.

In [17]:
conn.close()

In [20]:
db_path = '../data/checking-logs.sqlite'
conn = sqlite3.connect(db_path)

In [21]:
test = pd.io.sql.read_sql('SELECT * FROM test', conn)

In [22]:
control = pd.io.sql.read_sql('SELECT * FROM control', conn)

In [23]:
print(test)

        uid   labname             first_commit_ts               first_view_ts
0    user_1    laba04  2020-04-26 17:06:18.462708  2020-04-26 21:53:59.624136
1    user_1   laba04s  2020-04-26 17:12:11.843671  2020-04-26 21:53:59.624136
2    user_1    laba05  2020-05-02 19:15:18.540185  2020-04-26 21:53:59.624136
3    user_1    laba06  2020-05-17 16:26:35.268534  2020-04-26 21:53:59.624136
4    user_1   laba06s  2020-05-20 12:23:37.289724  2020-04-26 21:53:59.624136
5    user_1  project1  2020-05-14 20:56:08.898880  2020-04-26 21:53:59.624136
6   user_10    laba04  2020-04-25 08:24:52.696624  2020-04-18 12:19:50.182714
7   user_10   laba04s  2020-04-25 08:37:54.604222  2020-04-18 12:19:50.182714
8   user_10    laba05  2020-05-01 19:27:26.063245  2020-04-18 12:19:50.182714
9   user_10    laba06  2020-05-19 11:39:28.885637  2020-04-18 12:19:50.182714
10  user_10   laba06s  2020-05-20 07:37:31.175817  2020-04-18 12:19:50.182714
11  user_10  project1  2020-05-12 20:12:28.056618  2020-04-18 12:19:50.182714
12  user_14    laba04  2020-04-18 15:14:00.312338  2020-04-18 10:53:52.623447
13  user_14   laba04s  2020-04-18 22:30:30.247628  2020-04-18 10:53:52.623447
14  user_14    laba05  2020-04-30 11:33:04.523118  2020-04-18 10:53:52.623447
15  user_14  project1  2020-05-05 21:35:43.554986  2020-04-18 10:53:52.623447
16  user_17    laba04  2020-04-23 14:24:29.947554  2020-04-18 10:56:55.833899
17  user_17   laba04s  2020-04-25 12:10:56.414175  2020-04-18 10:56:55.833899
18  user_17    laba05  2020-05-02 13:21:24.045876  2020-04-18 10:56:55.833899
19  user_17    laba06  2020-05-21 15:21:31.567615  2020-04-18 10:56:55.833899
20  user_17   laba06s  2020-05-21 17:39:17.783615  2020-04-18 10:56:55.833899
21  user_17  project1  2020-04-18 07:56:45.408648  2020-04-18 10:56:55.833899
22  user_18    laba04  2020-04-26 19:48:11.822365  2020-04-26 22:49:29.243278
23  user_18   laba04s  2020-04-26 20:03:56.935458  2020-04-26 22:49:29.243278
24  user_18    laba05  2020-05-03 13:01:34.848756  2020-04-26 22:49:29.243278
25  user_18  project1  2020-05-11 10:10:04.166881  2020-04-26 22:49:29.243278
26  user_19    laba04  2020-04-20 19:05:01.297780  2020-04-21 20:30:38.034966
27  user_19    laba05  2020-05-02 15:16:13.586405  2020-04-21 20:30:38.034966
28  user_19    laba06  2020-05-19 10:25:54.121465  2020-04-21 20:30:38.034966
29  user_19   laba06s  2020-05-21 13:27:06.705881  2020-04-21 20:30:38.034966
30  user_19  project1  2020-05-14 10:33:45.495389  2020-04-21 20:30:38.034966
31  user_21    laba04  2020-04-21 17:48:00.487806  2020-04-22 22:40:36.824081
32  user_21   laba04s  2020-04-22 20:09:21.857747  2020-04-22 22:40:36.824081
33  user_21    laba05  2020-05-02 14:05:40.013959  2020-04-22 22:40:36.824081
34  user_21    laba06  2020-05-19 19:30:14.644328  2020-04-22 22:40:36.824081
35  user_21  project1  2020-05-10 15:21:05.442755  2020-04-22 22:40:36.824081
36  user_25    laba04  2020-04-20 19:16:50.673054  2020-05-09 23:54:54.260791
37  user_25   laba04s  2020-04-26 21:07:56.952117  2020-05-09 23:54:54.260791
38  user_25    laba05  2020-05-01 13:02:27.357650  2020-05-09 23:54:54.260791
39  user_25    laba06  2020-05-18 17:07:47.988807  2020-05-09 23:54:54.260791
40  user_25   laba06s  2020-05-20 14:02:26.512032  2020-05-09 23:54:54.260791
41  user_25  project1  2020-05-08 11:10:28.100852  2020-05-09 23:54:54.260791
42  user_28    laba04  2020-04-22 21:47:19.707242  2020-05-10 21:07:50.350946
43  user_28   laba04s  2020-04-26 15:53:44.906136  2020-05-10 21:07:50.350946
44  user_28    laba05  2020-05-01 18:29:11.968537  2020-05-10 21:07:50.350946
45  user_28    laba06  2020-05-17 17:08:48.257050  2020-05-10 21:07:50.350946
46  user_28   laba06s  2020-05-20 20:42:44.423160  2020-05-10 21:07:50.350946
47  user_28  project1  2020-05-12 14:42:19.166414  2020-05-10 21:07:50.350946
48   user_3    laba04  2020-04-23 20:29:14.054364  2020-05-08 10:53:47.123832
49   user_3   laba04s  2020-04-23 20:40:26.883591  2020-05-08 10:53:47.123832
50   user_3    laba05  2020-05-01 11:29:17.988118  2020-05-08 10:53:47.123832
51   user_3    laba06  2020-05-17 09:56:40.480319  2020-05-08 10:53:47.123832
52   user_3   laba06s  2020-05-19 08:42:50.851878  2020-05-08 10:53:47.123832
53   user_3  project1  2020-05-07 21:02:52.885133  2020-05-08 10:53:47.123832
54  user_30    laba04  2020-04-18 13:36:53.971502  2020-04-17 22:46:26.785035
55  user_30   laba04s  2020-04-18 14:51:37.498399  2020-04-17 22:46:26.785035
56  user_30    laba05  2020-05-01 19:31:18.375833  2020-04-17 22:46:26.785035
57  user_30    laba06  2020-05-19 17:53:15.088248  2020-04-17 22:46:26.785035
58  user_30  project1  2020-04-22 12:36:24.053518  2020-04-17 22:46:26.785035

In [24]:
print(control)

        uid   labname             first_commit_ts               first_view_ts
0   user_11    laba05  2020-05-03 21:06:55.970293  2020-04-27 00:40:05.761783
1   user_11  project1  2020-05-03 23:45:33.673409  2020-04-27 00:40:05.761783
2   user_12    laba04  2020-04-18 17:07:51.767358  2020-04-27 00:40:05.761783
3   user_12   laba04s  2020-04-26 15:42:38.070593  2020-04-27 00:40:05.761783
4   user_12    laba05  2020-05-03 08:39:25.174316  2020-04-27 00:40:05.761783
..      ...       ...                         ...                         ...
76   user_8   laba04s  2020-04-19 10:22:35.761944  2020-04-27 00:40:05.761783
77   user_8    laba05  2020-05-02 13:28:07.705193  2020-04-27 00:40:05.761783
78   user_8    laba06  2020-05-16 17:56:15.755553  2020-04-27 00:40:05.761783
79   user_8   laba06s  2020-05-16 20:01:07.900727  2020-04-27 00:40:05.761783
80   user_8  project1  2020-05-14 15:42:04.002981  2020-04-27 00:40:05.761783

[81 rows x 4 columns]