In [1]:
import pandas as pd

## read_csv:
- Отфильтруй строки с индексами 2 и 3 с помощью аргумента skiprows - мы знаем, что эти наблюдения были фейковыми.
- Отфильтруй последние две строки «хвоста» с помощью аргумента skipfooter - они тоже фейковые.
- Задай имена столбцов: datetime, user.
- Используй datetime как индексный столбец.

In [2]:
df = pd.read_csv('../data/feed-views.log', sep='\t', names=['datetime', 'user'], skiprows=[2, 3], skipfooter=2, index_col='datetime')
df.head()

/tmp/ipykernel_2215/3462130294.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  df = pd.read_csv('../data/feed-views.log', sep='\t', names=['datetime', 'user'], skiprows=[2, 3], skipfooter=2, index_col='datetime')

                              user
datetime
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

In [3]:
df.tail()

                                 user
datetime
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

## Переименуй datetime в date_time.

In [4]:
df.index.name = 'date_time'
df.head()

                              user
date_time
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

## to_csv:
- Используй в качестве разделителя символ ';'.
- Сохрани в файл feed-views-semicolon.log.

In [5]:
df.to_csv('../data/feed-views-semicolon.log', sep=';')

In [6]:
df.count()

user    1072
dtype: int64

In [7]:
df2 = pd.read_csv('../data/feed-views-semicolon.log', sep=';')
df2.head()

                    date_time    user
0  2020-04-17 12:01:08.463179   artem
1  2020-04-17 12:01:23.743946   artem
2  2020-04-17 12:35:52.735016   artem
3  2020-04-17 12:36:21.401412  oksana
4  2020-04-17 12:36:22.023355  oksana