In [29]:
import pandas as pd
import gc

## Прочитай файл fines.csv, который ты сохранил(а) в предыдущем упражнении.
- Во всех подпунктах далее тебе нужно вычислять fines/refund*year для каждой строки и создать новый столбец с рассчитанными данными.
- Измеряй время с помощью магической команды %%timeit в ячейке.
- Итерации:
    - Напиши функцию, которая проходит по DataFrame циклом for i in range(0, len(df)), использует iloc и append() в список. Результат функции присвой новому столбцу в DataFrame.
    - Сделай то же с использованием iterrows().
    - Сделай то же с использованием apply() и лямбда-функции.
    - Сделай то же, используя объекты Series из DataFrame.
    - Сделай как в предыдущем подпункте, но используй метод .values.

In [30]:
df = pd.read_csv('../data/fines.csv')
df.head()

      CarNumber  Refund   Fines    Make  Model  Year
0  Y163O8161RUS       2  3200.0    Ford  Focus  1989
1   E432XX77RUS       1  6500.0  Toyota  Camry  1995
2   7184TT36RUS       1  2100.0    Ford  Focus  1984
3  X582HE161RUS       2  2000.0    Ford  Focus  2015
4  92918M178RUS       1  5700.0    Ford  Focus  2014

In [31]:
def calculate_loop_iloc() -> list:
    results = []
    for i in range(0, len(df)):
        val = df.iloc[i]['Fines'] / df.iloc[i]['Refund'] * df.iloc[i]['Year']
        results.append(val)

    return results

In [32]:
%%timeit

df['result_loop'] = calculate_loop_iloc()

78.3 ms ± 272 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [33]:
df.head()

      CarNumber  Refund   Fines    Make  Model  Year  result_loop
0  Y163O8161RUS       2  3200.0    Ford  Focus  1989    3182400.0
1   E432XX77RUS       1  6500.0  Toyota  Camry  1995   12967500.0
2   7184TT36RUS       1  2100.0    Ford  Focus  1984    4166400.0
3  X582HE161RUS       2  2000.0    Ford  Focus  2015    2015000.0
4  92918M178RUS       1  5700.0    Ford  Focus  2014   11479800.0

In [34]:
def calculate_iterrows() -> list:
    results = []
    for _, row in df.iterrows():
        results.append(row['Fines'] / row['Refund'] * row['Year'])

    return results

In [35]:
%%timeit

df['result_iterrows'] = calculate_iterrows()

18.3 ms ± 142 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [36]:
df.head()

,CarNumber,Refund,Fines,Make,Model,Year,result_loop,result_iterrows
0,Y163O8161RUS,2,3200.0,Ford,Focus,1989,3182400.0,3182400.0
1,E432XX77RUS,1,6500.0,Toyota,Camry,1995,12967500.0,12967500.0
2,7184TT36RUS,1,2100.0,Ford,Focus,1984,4166400.0,4166400.0
3,X582HE161RUS,2,2000.0,Ford,Focus,2015,2015000.0,2015000.0
4,92918M178RUS,1,5700.0,Ford,Focus,2014,11479800.0,11479800.0

In [37]:
%%timeit

df['result_apply'] = df.apply(lambda row: row['Fines'] / row['Refund'] * row['Year'], axis=1)

4.28 ms ± 46.9 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [38]:
df.head()

,CarNumber,Refund,Fines,Make,Model,Year,result_loop,result_iterrows,result_apply
0,Y163O8161RUS,2,3200.0,Ford,Focus,1989,3182400.0,3182400.0,3182400.0
1,E432XX77RUS,1,6500.0,Toyota,Camry,1995,12967500.0,12967500.0,12967500.0
2,7184TT36RUS,1,2100.0,Ford,Focus,1984,4166400.0,4166400.0,4166400.0
3,X582HE161RUS,2,2000.0,Ford,Focus,2015,2015000.0,2015000.0,2015000.0
4,92918M178RUS,1,5700.0,Ford,Focus,2014,11479800.0,11479800.0,11479800.0

In [39]:
%%timeit

df['result_series'] = df['Fines'] / df['Refund'] * df['Year']

111 μs ± 1.51 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [40]:
df.head()

,CarNumber,Refund,Fines,Make,Model,Year,result_loop,result_iterrows,result_apply,result_series
0,Y163O8161RUS,2,3200.0,Ford,Focus,1989,3182400.0,3182400.0,3182400.0,3182400.0
1,E432XX77RUS,1,6500.0,Toyota,Camry,1995,12967500.0,12967500.0,12967500.0,12967500.0
2,7184TT36RUS,1,2100.0,Ford,Focus,1984,4166400.0,4166400.0,4166400.0,4166400.0
3,X582HE161RUS,2,2000.0,Ford,Focus,2015,2015000.0,2015000.0,2015000.0,2015000.0
4,92918M178RUS,1,5700.0,Ford,Focus,2014,11479800.0,11479800.0,11479800.0,11479800.0

In [41]:
%%timeit

df['result_values'] = df['Fines'].values / df['Refund'].values * df['Year'].values

52.8 μs ± 1.16 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [42]:
df.head()

,CarNumber,Refund,Fines,Make,Model,Year,result_loop,result_iterrows,result_apply,result_series,result_values
0,Y163O8161RUS,2,3200.0,Ford,Focus,1989,3182400.0,3182400.0,3182400.0,3182400.0,3182400.0
1,E432XX77RUS,1,6500.0,Toyota,Camry,1995,12967500.0,12967500.0,12967500.0,12967500.0,12967500.0
2,7184TT36RUS,1,2100.0,Ford,Focus,1984,4166400.0,4166400.0,4166400.0,4166400.0,4166400.0
3,X582HE161RUS,2,2000.0,Ford,Focus,2015,2015000.0,2015000.0,2015000.0,2015000.0,2015000.0
4,92918M178RUS,1,5700.0,Ford,Focus,2014,11479800.0,11479800.0,11479800.0,11479800.0,11479800.0

Выводы:
- **loop + iloc: 81.2 ms = 81200 μs** - самый медленный способ, поскольку каждый раз идёт обращение к датафрейму по индексу 
- **iterrows: 18.7 ms = 18700 μs** - быстрее цикла в 4 раза, но всё ещё недостаточно быстрый из-за того, что при каждой итерации строка превращается в Series
- **apply: 4.35 ms = 4350 μs** - быстрее iterrows в 4 раза, поскольку функция передаётся и выполняется на C за счёт особенностей реализации pandas, однако лямбда-функция всё равно вызывается на каждой итерации, что замедляет процесс
- **series: 113 μs** - быстрее apply в 38 раз, поскольку вычисления выполняются векторизованно над всем столбцом сразу на уровне numpy, но у pandas всё равно остаются траты времени на выравнивание индексов перед расчётами
- **values: 54 μs** - быстрее series в 2 раза,  поскольку .values извлекает чистый numpy-массив, и здесь не выполняется проверки типов и индексов

Итого: values быстрее цикла с обращением по индексу **в 1504 раза**, что в обработке больших данных будет сильно ощутимо

## Индексация: время также измеряй магической командой %%timeit в ячейке.
- Получи строку для конкретного CarNumber, например, "O136HO197RUS."
- Установи индекс в своём DataFrame столбцом CarNumber.
- Снова получи строку для того же CarNumber.

In [43]:
%%timeit

df[df["CarNumber"] == "O136HO197RUS"]

266 μs ± 1.59 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [44]:
df[df["CarNumber"] == "O136HO197RUS"]

,CarNumber,Refund,Fines,Make,Model,Year,result_loop,result_iterrows,result_apply,result_series,result_values
715,O136HO197RUS,2,7800.0,Toyota,Corolla,1999,7796100.0,7796100.0,7796100.0,7796100.0,7796100.0

In [45]:
df.set_index('CarNumber', inplace=True)

In [46]:
%%timeit

df.loc["O136HO197RUS"]

39.9 μs ± 257 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [47]:
df.loc["O136HO197RUS"]

Refund                     2
Fines                 7800.0
Make                  Toyota
Model                Corolla
Year                    1999
result_loop        7796100.0
result_iterrows    7796100.0
result_apply       7796100.0
result_series      7796100.0
result_values      7796100.0
Name: O136HO197RUS, dtype: object

Вывод: добавление индекса ускоряет обращение к объекту **в 7 раз**

## Понижение разрядности типов (downcasting):
- Выполни df.info(memory_usage='deep') и обрати внимание на Dtype и объём памяти.
- Создай copy() исходного DataFrame в другой DataFrame - optimized_df.
- Понизь разрядность типа с float64 до float32 для всех столбцов.
- Понизь разрядность типа с int64 до минимально возможного числового Dtype.
- Запусти info(memory_usage='deep') для нового DataFrame и обрати внимание на Dtype и объём памяти.

In [48]:
df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
Index: 930 entries, Y163O8161RUS to 12345X678RUS
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Refund           930 non-null    int64
 1   Fines            930 non-null    float64
 2   Make             930 non-null    str
 3   Model            919 non-null    str
 4   Year             930 non-null    int64
 5   result_loop      930 non-null    float64
 6   result_iterrows  930 non-null    float64
 7   result_apply     930 non-null    float64
 8   result_series    930 non-null    float64
 9   result_values    930 non-null    float64
dtypes: float64(6), int64(2), str(2)
memory usage: 243.4 KB

In [49]:
optimized_df = df.copy()

In [50]:
float_cols = optimized_df.select_dtypes(include=['float64']).columns

optimized_df[float_cols] = optimized_df[float_cols].astype('float32')

In [51]:
int_cols = optimized_df.select_dtypes(include=['int64']).columns

for col in int_cols:
    optimized_df[col] = pd.to_numeric(
        optimized_df[col],
        downcast='integer'
    )

In [52]:
optimized_df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
Index: 930 entries, Y163O8161RUS to 12345X678RUS
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Refund           930 non-null    int8
 1   Fines            930 non-null    float32
 2   Make             930 non-null    str
 3   Model            919 non-null    str
 4   Year             930 non-null    int16
 5   result_loop      930 non-null    float32
 6   result_iterrows  930 non-null    float32
 7   result_apply     930 non-null    float32
 8   result_series    930 non-null    float32
 9   result_values    930 non-null    float32
dtypes: float32(6), int16(1), int8(1), str(2)
memory usage: 209.8 KB

Вывод: уменьшение диапазона числовых типов данных не сильно повлияло на занимаемую датафреймом память: пожертвовать 33,6 KB ради большего диапазона значений признаков в будущем звучит нормально

## Категории:
- Преобразуй столбцы типа object в category.
- На этот раз проверь объём памяти. Вероятно, он уменьшится в 2-3 раза по сравнению с исходным DataFrame.

In [53]:
str_cols = optimized_df.select_dtypes(include=['str']).columns

optimized_df[str_cols] = optimized_df[str_cols].astype('category')

optimized_df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
Index: 930 entries, Y163O8161RUS to 12345X678RUS
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Refund           930 non-null    int8
 1   Fines            930 non-null    float32
 2   Make             930 non-null    category
 3   Model            919 non-null    category
 4   Year             930 non-null    int16
 5   result_loop      930 non-null    float32
 6   result_iterrows  930 non-null    float32
 7   result_apply     930 non-null    float32
 8   result_series    930 non-null    float32
 9   result_values    930 non-null    float32
dtypes: category(2), float32(6), int16(1), int8(1)
memory usage: 114.7 KB

Вывод: изменение строкового типа на категориальный привело к уменьшению памяти в 2 раза, что на больших данных будет существенно

## Очистка памяти:
- Используя библиотеку gc и команду %reset_selective, удали из памяти только свой исходный DataFrame

In [54]:
%reset_selective -f ^df$
gc.collect()

222

In [55]:
%whos

Variable              Type         Data/Info
--------------------------------------------
calculate_iterrows    function     <function calculate_iterrows at 0x7f7403fefce0>
calculate_loop_iloc   function     <function calculate_loop_iloc at 0x7f740405c040>
col                   str          Year
float_cols            Index        Index(['Fines', 'result_l<...>es'],\n      dtype='str')
gc                    module       <module 'gc' (built-in)>
int_cols              Index        Index(['Refund', 'Year'], dtype='str')
optimized_df          DataFrame    Shape: (930, 10)
pd                    module       <module 'pandas' from '/h<...>ages/pandas/__init__.py'>
str_cols              Index        Index(['Make', 'Model'], dtype='str')

In [56]:
df.head()

NameError: name 'df' is not defined